### ISSUE TITLE
Feature request: generate a virtual datasheet (pdf-file) 

### ISSUE THREAD

**Issue by gituser789** [upb-lea/transistordatabase#14]
function available but not compleated
(graphs are missing)

**Comment by gituser789** [comment]
Please Sort the datasheet values, make some sections:
 - Standard stuff: Manufacturer, Type, Datasheet date, Datasheet Hyperlink, 
 - Mechanical and thermal: Housing_area, Housing_type, R_th_xxxxx
 - maximum ratings (I_abs_max, V_abs_max, T_j_max, T_c_max)
 - Capacitances: C_iss_fix, ....
 - all the rest

**Comment by gituser789** [comment]
Replace the 'programming variable names' by real datasheet names (clean symbols)
e.g.
C_iss_fix -> italic: 'C', subscript 'iss,fix'
Is this possible?

**Comment by gituser789** [comment]
- in 'Created by', insert 'LEA' department incl. Link to Homepage (https://ei.uni-paderborn.de/lea) instead of the actual name
- Remove 'Mail ID' from the pdf

**Comment by gituser789** [comment]
Just provide the english language in the virtual datasheet 
(remove 'Technische Information')

**Comment by gituser789** [comment]
Check Format: A4?
graph_r_e missing

**Comment by gituser789** [comment]
Add hint: 'This document is not the official datasheet
'

**Comment by gituser789** [comment]
Unit of R_th_xx is K/W

**Comment by gituser789** [comment]
Sorting switch conduction for temperatures is really nice!
please implement this also for the diode

Switch:
![image](https://user-images.githubusercontent.com/62549000/128322520-56611bac-f08f-45fb-8763-312f8da9c11c.png)

Diode:
![image](https://user-images.githubusercontent.com/62549000/128323084-dd3f2d14-fac1-4777-ba49-76d33f2991e2.png)

**Comment by gituser789** [comment]
Page break in case of too much graphs necessary

**Comment by MohanNagella** [comment]
Fixed and updated!
