### ISSUE TITLE
Problem in Windows when removing cloned repo

### ISSUE THREAD

**Issue by gituser789** [upb-lea/transistordatabase#19]
in update_from_fileexchange(), when shutil.rmtree('./cloned_repo'):
PermissionError: [WinError 5] Zugriff verweitert: './cloned_repo\\.git\\objects\\pack-xxxxxx.idx'

Seems to be only at first run when there was a problem with mongodb. Repo was cloned, but update_from_fileexchange() runs into error due to not installed mongo (or connection to service was not possible due to mongo not running)

May this is a solution
https://stackoverflow.com/questions/1213706/what-user-do-python-scripts-run-as-in-windows

**Comment by MohanNagella** [comment]
Fixed with commit #d6b0d90(Cloned repo: git pull and clone additions)
