### ISSUE TITLE
Plecs exporter: wrong folder path issue

### ISSUE THREAD

**Issue by MohanNagella** [upb-lea/transistordatabase#32]
Templates switchTemplate.txt and diodeTemplate.txt aren't fetched by the exporter function because of miss placing the files in the wrong folder path.

**Comment by gituser789** [comment]
Actual there is a second problem (in a not-pushed pre-test) with adding the .txt files to the pip package:
Here is the solution: (see No. 4)
https://izziswift.com/including-non-python-files-with-setup-py/
The files must be versioned in git
