### ISSUE TITLE
Recheck type hints

### ISSUE THREAD

**Issue by gituser789** [upb-lea/transistordatabase#42]
Wrong:
```v_abs_max: [float, int]```
first, for X OR Y, Union must be used, second, float includes int.
https://stackoverflow.com/questions/50928592/mypy-type-hint-unionfloat-int-is-there-a-number-type
Correct:
```v_abs_max: [float]```

Wrong:
```comment: [str, None]```
Better
```comment: Union[str, None]``` or ```comment: Optional[str]```
https://stackoverflow.com/questions/51710037/how-should-i-use-the-optional-type-hint

Also the list type hints are not correct.

Check: https://www.python.org/dev/peps/pep-0484/

Also in Pyhton 3.9, the typing package is in standard collection: https://www.python.org/dev/peps/pep-0585/
Introduction why the new pep: https://www.python.org/dev/peps/pep-0585/#rejected-alternatives
section about 'list' and 'List': https://www.python.org/dev/peps/pep-0585/#generics-erasure

please comment this issue for more information

**Comment by MKlaedtke** [comment]
You can also add type hints to function arguments and returns like specified in PEP 484.
For example
`def isvalid_dict(dataset_dict, dict_type):`
would become
`def isvalid_dict(dataset_dict: dict, dict_type: dict) -> bool:`

**Comment by gituser789** [comment]
Update first comment:
Wrong:
v_abs_max: [float, int]
first, for X OR Y, Union must be used, second, float includes int.
https://stackoverflow.com/questions/50928592/mypy-type-hint-unionfloat-int-is-there-a-number-type
Correct:
v_abs_max: float

**Comment by gituser789** [comment]
Make the comment next to type-hints compatible with sphinx:
There is a ```#:``` needed as comment line
https://stackoverflow.com/questions/24080491/print-the-variable-value-in-a-sphinx-document

**Comment by gituser789** [comment]
https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html

**Comment by gituser789** [comment]
Find out how to give numpy-type-hints.
may this helps:    https://numpy.org/devdocs/reference/typing.html

**Comment by MohanNagella** [comment]
Left with weak warnings
