### ISSUE TITLE
GeckoCircuits temperature interpolation not working for all transistors from TDB

### ISSUE THREAD

**Issue by gituser789** [upb-lea/transistordatabase#74]
**Describe the bug**
Some termperature interpolations inside geckocircuits are not working for all transistors.
Currently is is not clear if there is a bug in geckocircuits or inside the TDB.

**To Reproduce**
1. load transistor CREE_C3M0065100J 
2. export it to geckoCircuits with r_g = 3 Ohms (may also default r_g works)
3. load data into geckocircuits
4. Interpolate the channel for other temperatures (90°C in the screenshot example) - this is not working
5. Find out if the problem is within geckocircuits or the data export from the TDB
6. The same procedure works for CREE_C3M0060065J!
7. See Screenshots!

**Expected behavior**
Temperature interpolation works fine

**Desktop (please complete the following information):**
Current development version of TDB

![image](https://user-images.githubusercontent.com/62549000/148755645-976f7577-87bc-4cab-8292-67d09bb25a13.png)
![image](https://user-images.githubusercontent.com/62549000/148755709-033c94db-2095-4834-821c-06f9dce209e1.png)

**Comment by MohanNagella** [comment]
Possible issue with Gecko Circuits as no issue found with the code lines #1678-1681 which copy the channel curves from the existing database

**Comment by MohanNagella** [comment]
![working_CREE_C3M0065100J_positive_80Tj](https://user-images.githubusercontent.com/78087426/149812247-61b9bce3-2e66-4b97-97f6-581feb7f3c97.PNG)
